name = "browser-rendering-api"
main = "puppeteer-worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "browser"

[[kv_namespaces]]
binding = "SCREENSHOTS"
id = "a1a04bb7cb8046d4915109472e9f0789"
